import type { Thread } from '../../lib/api';

export const DEMO_THREADS: Thread[] = [
  {
    id: 'demo-analytics-cockpit',
    title: 'Product analytics cockpit',
    sender: 'Alice Chen',
    subject: 'A clearer read on product health',
    preview: 'We need one place to see activation, retention, and the signals that move them.',
    status: 'waiting_for_me',
    completeness: 72,
    unread_count: 3,
    question_count: 2,
    updated_at: '2026-09-11T09:36:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-analytics-cockpit',
    category: 'ANALYTICS',
  },
  {
    id: 'demo-vendor-onboarding',
    title: 'Vendor onboarding flow',
    sender: 'Marcus Lee',
    subject: 'Reduce the first-week setup drag',
    preview: 'The handoff between sales and operations is still mostly a chain of forwarded emails.',
    status: 'ready',
    completeness: 94,
    unread_count: 1,
    question_count: 0,
    updated_at: '2026-09-11T08:48:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-vendor-onboarding',
    category: 'OPERATIONS',
  },
  {
    id: 'demo-mobile-brief',
    title: 'Mobile brief builder',
    sender: 'Priya Raman',
    subject: 'A small tool for better briefs',
    preview: 'Could we make the brief feel more like a guided conversation than another form?',
    status: 'waiting_for_me',
    completeness: 58,
    unread_count: 4,
    question_count: 3,
    updated_at: '2026-09-10T18:22:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-mobile-brief',
    category: 'PRODUCT',
  },
  {
    id: 'demo-revenue-forecast',
    title: 'Revenue forecast view',
    sender: 'Noah Williams',
    subject: 'Planning for the next operating review',
    preview: 'Finance needs a calm, auditable view of the assumptions behind the next forecast.',
    status: 'replied',
    completeness: 100,
    unread_count: 0,
    question_count: 1,
    updated_at: '2026-09-10T16:05:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-revenue-forecast',
    category: 'FINANCE',
  },
  {
    id: 'demo-support-triage',
    title: 'Support triage signals',
    sender: 'Sofia Ortega',
    subject: 'Spot the issues before the queue grows',
    preview: 'We are looking for a lightweight signal layer over the support queue, not another inbox.',
    status: 'waiting_for_me',
    completeness: 66,
    unread_count: 2,
    question_count: 1,
    updated_at: '2026-09-10T13:40:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-support-triage',
    category: 'CUSTOMER',
  },
  {
    id: 'demo-brand-library',
    title: 'Brand library refresh',
    sender: 'Jules Martin',
    subject: 'A more usable source of truth',
    preview: 'The team needs one place for the latest patterns, with enough context to make a good call.',
    status: 'ready',
    completeness: 86,
    unread_count: 1,
    question_count: 0,
    updated_at: '2026-09-10T11:18:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-brand-library',
    category: 'BRAND',
  },
  {
    id: 'demo-api-observability',
    title: 'API observability pass',
    sender: 'Ethan Kim',
    subject: 'Where did the latency go?',
    preview: 'A small, shared view could help engineering see regressions before customers do.',
    status: 'no_action',
    completeness: 34,
    unread_count: 0,
    question_count: 0,
    updated_at: '2026-09-09T17:26:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-api-observability',
    category: 'PLATFORM',
  },
  {
    id: 'demo-customer-notes',
    title: 'Customer notes, in context',
    sender: 'Maya Patel',
    subject: 'Connect the conversation to the account',
    preview: 'The note is useful only when it arrives alongside the account and the last decision.',
    status: 'waiting_for_me',
    completeness: 63,
    unread_count: 5,
    question_count: 2,
    updated_at: '2026-09-09T14:12:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-customer-notes',
    category: 'CUSTOMER',
  },
  {
    id: 'demo-release-notes',
    title: 'Release notes ritual',
    sender: 'Theo Brown',
    subject: 'Let every launch tell a better story',
    preview: 'We want to make the impact of each release legible without adding another ceremony.',
    status: 'replied',
    completeness: 91,
    unread_count: 0,
    question_count: 1,
    updated_at: '2026-09-09T10:07:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-release-notes',
    category: 'PRODUCT',
  },
  {
    id: 'demo-workshop-scheduling',
    title: 'Workshop scheduling',
    sender: 'Lena Fischer',
    subject: 'Less back-and-forth, more making',
    preview: 'A simple shared rhythm would save the team a surprising amount of time each week.',
    status: 'waiting_for_me',
    completeness: 49,
    unread_count: 2,
    question_count: 2,
    updated_at: '2026-09-08T19:34:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-workshop-scheduling',
    category: 'OPERATIONS',
  },
  {
    id: 'demo-permission-audit',
    title: 'Permission audit trail',
    sender: 'Samira Okafor',
    subject: 'A little more confidence around access',
    preview: 'The audit should answer who changed what, without making every admin a detective.',
    status: 'do_not_reply',
    completeness: 78,
    unread_count: 1,
    question_count: 0,
    updated_at: '2026-09-08T15:51:00+08:00',
    do_not_reply: true,
    requirement_id: 'req-demo-permission-audit',
    category: 'PLATFORM',
  },
  {
    id: 'demo-research-repository',
    title: 'Research repository',
    sender: 'Oliver Grant',
    subject: 'Keep the why close to the work',
    preview: 'We have the interviews; the missing piece is an easy way to carry the signal forward.',
    status: 'ready',
    completeness: 88,
    unread_count: 1,
    question_count: 0,
    updated_at: '2026-09-08T11:29:00+08:00',
    do_not_reply: false,
    requirement_id: 'req-demo-research-repository',
    category: 'RESEARCH',
  },
];
